apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: our-nginx
    repo: /Users/karolkielbasa/Documents/argoCD/argocd-core-cluster-management/our-nginx
    namespace: our-nginx
    version: 0.1.0
    valuesFile: values.yaml
